sudo: false
dist: trusty
language: node_js
node_js: "10"
script: 
  - npm test
  - npm run lint
after_success: 
  - npm run codecov
before_deploy: 
  - npm run increment
  - npm run build
deploy:
  - provider: npm
    skip_cleanup: true
    email: yotammann@gmail.com
    api_key: $NPM_TOKEN
    on:
      repo: Tonejs/Midi
      # don't publish on cron or PRs
      condition: $TRAVIS_EVENT_TYPE != cron && $TRAVIS_EVENT_TYPE != pull_request
